SCALE Job started on Sat 04/04/2026 11:24:04
With Host name DESKTOP-7IM1PK5
working directory /tmp/scale.jonathon.649534
and process id 649534.
Input file named /home/jonathon/projects/MonteCarloXenon/omc_fhr/corrector/corrector.inp
and output file named /home/jonathon/projects/MonteCarloXenon/omc_fhr/corrector/corrector.out
##########################################################
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
  Now executing origen                          
